"""
VNSA 2.0 — Document Generation Tool
Generates .md, .txt, .html, .docx, .pdf files and saves to ~/Documents/VNSA/
"""
import os
from datetime import datetime
from pathlib import Path

OUTPUT_DIR = Path.home() / "Documents" / "VNSA"

TOOL_DEFINITION = {
    "name": "generate_document",
    "description": (
        "Generate and save documents: markdown, plain text, HTML, Word (.docx), or PDF. "
        "Use when Sir asks to create a report, letter, summary, or any document."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "format": {
                "type": "string",
                "enum": ["md", "txt", "html", "docx", "pdf"],
                "description": "Output format"
            },
            "filename": {
                "type": "string",
                "description": "Filename without extension, e.g. 'Q3_Report'"
            },
            "content": {
                "type": "string",
                "description": "Full document content (markdown or plain text)"
            },
            "title": {
                "type": "string",
                "description": "Document title for docx/pdf headers"
            },
        },
        "required": ["format", "filename", "content"],
    },
}


def run(format: str, filename: str, content: str, title: str = "") -> str:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Sanitise filename
    safe = "".join(c for c in filename if c.isalnum() or c in "._- ")
    safe = safe.strip().replace(" ", "_") or "document"

    if format == "md":
        return _write_md(safe, content)
    if format == "txt":
        return _write_txt(safe, content)
    if format == "html":
        return _write_html(safe, content, title or safe)
    if format == "docx":
        return _write_docx(safe, content, title or safe)
    if format == "pdf":
        return _write_pdf(safe, content, title or safe)
    return f"Unknown format: {format}"


def _write_md(name: str, content: str) -> str:
    path = OUTPUT_DIR / f"{name}.md"
    path.write_text(content, encoding="utf-8")
    return f"✅ Saved: {path}\n\nOpen with any Markdown viewer or VS Code."


def _write_txt(name: str, content: str) -> str:
    path = OUTPUT_DIR / f"{name}.txt"
    path.write_text(content, encoding="utf-8")
    return f"✅ Saved: {path}"


def _write_html(name: str, content: str, title: str) -> str:
    # Convert basic markdown to HTML
    html = _md_to_html(content)
    page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; max-width: 860px;
         margin: 40px auto; color: #1e293b; line-height: 1.7; padding: 0 20px; }}
  h1,h2,h3 {{ color: #0f172a; }}
  code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }}
  pre  {{ background: #f1f5f9; padding: 16px; border-radius: 8px; overflow-x: auto; }}
  blockquote {{ border-left: 3px solid #38bdf8; margin-left: 0; padding-left: 16px; color: #64748b; }}
  table {{ border-collapse: collapse; width: 100%; }}
  td,th {{ border: 1px solid #e2e8f0; padding: 8px 12px; }}
  th {{ background: #f8fafc; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p style="color:#94a3b8;font-size:0.85em">Generated by VNSA 2.0 — {datetime.now().strftime('%d %B %Y, %H:%M')}</p>
<hr>
{html}
</body>
</html>"""
    path = OUTPUT_DIR / f"{name}.html"
    path.write_text(page, encoding="utf-8")
    return f"✅ Saved: {path}\n\nOpen in any browser."


def _write_docx(name: str, content: str, title: str) -> str:
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()

        # Title
        t = doc.add_heading(title, 0)
        t.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Subtitle
        sub = doc.add_paragraph(
            f"Generated by VNSA 2.0 — {datetime.now().strftime('%d %B %Y, %H:%M')}"
        )
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub.runs[0].font.color.rgb = RGBColor(0x94, 0xa3, 0xb8)
        sub.runs[0].font.size = Pt(9)

        doc.add_paragraph()  # spacer

        # Parse content
        for line in content.split("\n"):
            stripped = line.strip()
            if stripped.startswith("### "):
                doc.add_heading(stripped[4:], level=3)
            elif stripped.startswith("## "):
                doc.add_heading(stripped[3:], level=2)
            elif stripped.startswith("# "):
                doc.add_heading(stripped[2:], level=1)
            elif stripped.startswith("- ") or stripped.startswith("* "):
                p = doc.add_paragraph(stripped[2:], style="List Bullet")
            elif stripped and stripped[0].isdigit() and ". " in stripped[:4]:
                p = doc.add_paragraph(stripped, style="List Number")
            elif stripped == "---":
                doc.add_paragraph("─" * 60)
            else:
                p = doc.add_paragraph(stripped)
                # Bold handling
                if "**" in stripped:
                    p.clear()
                    _add_bold_run(p, stripped)

        path = OUTPUT_DIR / f"{name}.docx"
        doc.save(str(path))
        return f"✅ Saved: {path}"
    except ImportError:
        return ("python-docx not installed. Run: pip install python-docx\n"
                "Alternatively I can save as .html or .md instead.")


def _write_pdf(name: str, content: str, title: str) -> str:
    # Try weasyprint, fall back to fpdf2, fall back to HTML
    html_content = _md_to_html(content)
    page = f"""<!DOCTYPE html><html><head><meta charset="UTF-8">
<style>
body {{ font-family: Arial, sans-serif; margin: 2cm; color: #1e293b; line-height: 1.6; }}
h1 {{ color: #0f172a; border-bottom: 2px solid #38bdf8; padding-bottom: 6px; }}
h2,h3 {{ color: #334155; }}
code {{ background: #f1f5f9; padding: 1px 4px; border-radius: 3px; }}
</style></head><body>
<h1>{title}</h1>
<p style="color:#94a3b8;font-size:0.8em">VNSA 2.0 — {datetime.now().strftime('%d %B %Y')}</p>
<hr>{html_content}</body></html>"""

    try:
        import weasyprint
        path = OUTPUT_DIR / f"{name}.pdf"
        weasyprint.HTML(string=page).write_pdf(str(path))
        return f"✅ Saved: {path}"
    except ImportError:
        pass

    try:
        from fpdf import FPDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, title, ln=True, align="C")
        pdf.set_font("Arial", "I", 9)
        pdf.cell(0, 6, f"VNSA 2.0 — {datetime.now().strftime('%d %B %Y')}", ln=True, align="C")
        pdf.ln(4)
        pdf.set_font("Arial", size=11)
        for line in content.split("\n"):
            stripped = line.strip()
            if stripped.startswith("# "):
                pdf.set_font("Arial", "B", 14)
                pdf.cell(0, 8, stripped[2:], ln=True)
                pdf.set_font("Arial", size=11)
            elif stripped.startswith("## "):
                pdf.set_font("Arial", "B", 12)
                pdf.cell(0, 7, stripped[3:], ln=True)
                pdf.set_font("Arial", size=11)
            elif stripped:
                pdf.multi_cell(0, 6, stripped)
            else:
                pdf.ln(3)
        path = OUTPUT_DIR / f"{name}.pdf"
        pdf.output(str(path))
        return f"✅ Saved: {path}"
    except ImportError:
        pass

    # Last resort: save as HTML and tell user
    html_path = OUTPUT_DIR / f"{name}.html"
    html_path.write_text(page, encoding="utf-8")
    return (f"PDF libraries not installed (pip install weasyprint or fpdf2).\n"
            f"Saved as HTML instead: {html_path}\n"
            f"You can print to PDF from your browser.")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _md_to_html(md: str) -> str:
    """Basic markdown → HTML conversion."""
    import re
    lines = md.split("\n")
    out = []
    in_list = False
    for line in lines:
        s = line.strip()
        if s.startswith("### "): out.append(f"<h3>{s[4:]}</h3>"); in_list=False
        elif s.startswith("## "): out.append(f"<h2>{s[3:]}</h2>"); in_list=False
        elif s.startswith("# "):  out.append(f"<h1>{s[2:]}</h1>"); in_list=False
        elif s.startswith("- ") or s.startswith("* "):
            if not in_list: out.append("<ul>"); in_list=True
            out.append(f"<li>{s[2:]}</li>")
        elif s == "---": out.append("<hr>"); in_list=False
        elif s:
            if in_list: out.append("</ul>"); in_list=False
            s = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', s)
            s = re.sub(r'\*(.+?)\*', r'<em>\1</em>', s)
            s = re.sub(r'`(.+?)`', r'<code>\1</code>', s)
            out.append(f"<p>{s}</p>")
        else:
            if in_list: out.append("</ul>"); in_list=False
    if in_list: out.append("</ul>")
    return "\n".join(out)


def _add_bold_run(paragraph, text: str):
    """Add runs with bold formatting for **text** markers."""
    import re
    parts = re.split(r'(\*\*[^*]+\*\*)', text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        else:
            paragraph.add_run(part)
